services:

  web:
    image: nginx:1.29-alpine
    restart: always
    network_mode: "host"
    environment:
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - html:/usr/share/nginx/html
      - certbot:/var/www/certbot/:ro
      - certs:/etc/nginx/ssl/:ro
      - conf:/etc/nginx/conf.d

  certbot:
    image: certbot/certbot:v4.2.0
    volumes:
      - certbot:/var/www/certbot
      - certs:/etc/letsencrypt

volumes:
  html:
  certbot:
  certs:
  conf:
